### ISSUE TITLE
Multi-line codeblocks width formatting

### ISSUE THREAD

**Issue by Loki-101** [doggybootsy/enhancecodeblocks#1]
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/59907407/4452ece9-684c-4dbf-af40-ecba1bab6e38)

Codeblocks created with `text` or ``text`` expand all the way to the right side of the screen, but codeblocks created with ```text``` are limited as shown in the screenshot. I _think_ the width property is being inherited from the one Discord set, as Discord has the same behavior. The problem is unlike default Discord this plugin cuts text off and has you use a scrollbar instead of making the code block taller to fit everything, so you can't really see the message in the preview.

**Comment by doggybootsy** [comment]
I have noticed this issue, but I haven't found a way to fix it yet

**Comment by Loki-101** [comment]
Fixed in https://github.com/doggybootsy/enhancecodeblocks/commit/7a5e101b5ca421e1ad3d8720f3ebffda9eb82b50

Thanks :D

I went back and found the original message I used as an example for comparison. The width still is limited like default Discord, but now it wraps around like default Discord so it's still readable.

Before:
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/59907407/ecb24f00-f88e-4cf2-9dd1-24275b1d61e1)


After: 
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/59907407/d3ead98a-235b-4c6f-a759-32553f15eb09)

**Comment by doggybootsy** [comment]
thats so strange, that update just added a style for wrapping text
