### ISSUE TITLE
Warnings instead of icons

### ISSUE THREAD

**Issue by sionit1337** [doggybootsy/enhancecodeblocks#4]
In plugin settings 
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/128901310/94903fff-aa4c-4b3a-a84a-0597130b0e53)

In codeblocks
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/128901310/0a4d9826-7f46-4560-9b02-1bbb314bff37)

**Comment by doggybootsy** [comment]
In a few days I'll remove the code that displays those warning icons. So instead of searching for icons in webpack I'll just make them use a local copy.

**Comment by doggybootsy** [comment]
Fixed with latest push
