### ISSUE TITLE
Spoilered code blocks can't be unspoilered

### ISSUE THREAD

**Issue by demize** [doggybootsy/enhancecodeblocks#7]
Perhaps a bit of an edge case, but I just ran into a couple spoilers I couldn't unspoil, and after a bit of digging I realized it's because they were code blocks. This is reproducible through the following input:

    ||```
    broken spoiler!
    ```||

This results in an empty dark grey box, with contents that cannot be revealed except by disabling the extension.

**Comment by doggybootsy** [comment]
Fixed in latest push
