### ISSUE TITLE
Plugin breaks "enhanced" markdown (links, headers, lists)

### ISSUE THREAD

**Issue by demize** [doggybootsy/enhancecodeblocks#8]
As of a couple days ago, this plugin breaks Discord's "enhanced" markdown functionality. Normal markdown (bold, italic, code blocks, etc) still works, but the enhanced markdown (links, headers, lists) renders in plain text with this plugin enabled.

**Comment by doggybootsy** [comment]
Weird that shouldn't happen but I can look at that later

**Comment by demize** [comment]
Yeah, it's weird. I bisected my plugin list to figure out what the cause was, only happens with this enabled (and always happens with this enabled).

Of course, a Discord update just broke BD entirely for me, so... no rush :)

**Comment by doggybootsy** [comment]
I don't get this issue
![image](https://github.com/doggybootsy/enhancecodeblocks/assets/71196819/6289d9da-7de9-4a2b-8cfa-0c8519b7d122)

**Comment by demize** [comment]
Hmm. Might be a conflict of some sort... with enhanceCodeBlocks disabled it's fine, with enhanceCodeBlocks and only enhanceCodeBlocks enabled it seems fine, but with my full plugin list it seems to still be messed up. I'll try to figure out what could be conflicting, but I guess it's probably not an issue with your plugin.

**Comment by doggybootsy** [comment]
If you find out what plugin it is, I can try to add some support thing to make it work. But I would assume that the plugin that's causing the issues is another plugin that touches markdown
